### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cpr-fer** [ajtudela/sicks300_2#1]
HI Alberto,

I was wondering if you were planning to publish this code under an Open Source License, e.g. Apache

**Comment by ajtudela** [comment]
Hi, 

Sorry for the delay. I'm not sure about the license of the ROS1 version. I'll checked it and I'll tell you.

**Comment by cpr-fer** [comment]
Thank you :) I'm assuming [this](https://github.com/ipa320/cob_driver/tree/kinetic_dev/cob_sick_s300) is the original repo, so would that mean you are keeping the Apache 2.0 license for your project?

Many thanks

Edit: I just noticed you already had added the Apache license file to the humble branch, I just checked the dev one, sorry
